rv/rv/config/routes.rb
Rv::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'static_pages#index'
  get "academics/video"
  get "academics/videos"
  get "academics/images"
  get "academics/videoteaser"
  get "transactions/karvy1"
  get "transactions/cams1"
  match '/',    to: 'static_pages#index',    via: 'get'
  match '/',    to: 'static_pages#index',    via: 'post'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/products', to: 'static_pages#products', via: 'get'
  match '/account', to: 'static_pages#account', via: 'get'
  match '/sip_registration', to: 'static_pages#sip_registration', via: 'get'
  match '/import_sip_registration', to: 'static_pages#import_sip_registration', via: 'post'
  match '/import_sip_transaction', to: 'static_pages#import_sip_transaction', via: 'post'
  match '/sip_transactions', to: 'static_pages#sip_transactions', via: 'get'
  match '/portfolio', to: 'static_pages#portfolio', via: 'get'
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  get "contacts/welcome_email"
  resources :kycs
  resources :kyc_steps
  resources :funds
  post "kycs/update_holding_type"
  post "kycs/new"
  resources :banks
  resources :transactions do 
    collection do
      get :investment
      post :invoice
      post :edit_individual
      post :update_individual
      get :ru
      post :ru
      post :confirmation
      post :cams_upload_feed
      post :cams_import_feed
      post :transact
      get :switch
      post :switch_transact
      post :karvy_upload_feed
    end
  end

  

end

rv/rv/app/models/bank.rb
class Bank < ActiveRecord::Base
	validates_presence_of :name_of_bank ,:account_num , :account_type ,:mode_of_holding,
	 :first_holder,:branch_address, :city, :ifsc_code, :micr_code,:sip_validity, :sip_upper_limit

	 

	 
end

rv/rv/app/models/cams_data.rb
class CamsData < ActiveRecord::Base
end

rv/rv/app/models/camsfeed.rb
class Camsfeed < ActiveRecord::Base
	
	def self.import(file)
	  allowed_attributes = [ "amc_code","folio_no","prodcode","scheme","inv_name","trxntype","trxnno","trxnmode",	"trxnstat",
	  	"usercode",	"usrtrxno",	"traddate",	"postdate",	"purprice",	"units",	"amount",	"brokcode",	"subbrok"	,"brokperc",
	  	"brokcomm",	"altfolio"	,"rep_date",	"time1",	"trxnsubtyp",	"application_no",	"trxn_nature",	"tax",	"total_tax",
	  	"te_15h",	"micr_no",	"remarks",	"swflag",	"old_folio",	"seq_no",	"reinvest_flag",	"mult_brok",	"stt",	"location",
	  	"scheme_type",	"tax_status",	"load",	"scanrefno",	"pan",	"inv_iin"	,"targ_src_scheme",	"trxn_type_flag",
	  	"ticob_trtype",	"ticob_trno",	"ticob_posted_date",	"dp_id",	"trxn_charges",	"eligib_amt",	"src_of_txn",	"trxn_suffix",
	  	"siptrxnno",	"ter_location",	"euin",	"euin_valid",	"euin_opted",	"sub_brk_arn"]
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    camsfeed = Camsfeed.new
	    camsfeed.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
	    camsfeed.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
	  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end

	
end

rv/rv/app/models/city_master.rb
class CityMaster < ActiveRecord::Base
end

rv/rv/app/models/contact.rb
class Contact < ActiveRecord::Base
end

rv/rv/app/models/due_transaction.rb
class DueTransaction < ActiveRecord::Base
end

rv/rv/app/models/feed.rb
class Feed < ActiveRecord::Base
end

rv/rv/app/models/fund.rb
class Fund < ActiveRecord::Base
end

rv/rv/app/models/holding.rb
class Holding < ActiveRecord::Base
end

rv/rv/app/models/karvy_data.rb
class KarvyData < ActiveRecord::Base
end

rv/rv/app/models/karvyfeed.rb
class Karvyfeed < ActiveRecord::Base
end

rv/rv/app/models/kyc.rb
class Kyc < ActiveRecord::Base

 	validates_presence_of :first_name, :last_name,:pan, :if => :active_or_general?
 	validates_format_of :pan, :with => /\A([A-Za-z]{5}\d{4}[A-Za-z]{1})\Z/i, :if => :active_or_general?
 	validates_presence_of :father_spouse_name,:nationality, :if => :active_or_personal?
	validates_presence_of :c_house_no, :c_street_name, :c_area_name,:c_email,:c_postal_code, :if => :active_or_c_address?
	validates_format_of :c_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :if => :active_or_c_address? 
	validates_format_of :c_postal_code, :with => /\A(\d{6})\Z/i, :if => :active_or_c_address? 
	validates_presence_of :c_mobile, :if => :active_or_c_address? 
	validates_presence_of :p_house_no, :p_street_name, :p_area_name,:p_email,:p_postal_code, :if => :active_or_p_address?
	validates_format_of :p_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :if => :active_or_p_address? 
	validates_format_of :p_postal_code, :with => /\A(\d{6})\Z/i, :if => :active_or_p_address? 
	validates_presence_of :p_mobile, :if => :active_or_p_address? 
	validates_presence_of :nominee_name,:nominee_relation,:nominee_address, :if => :active_or_nominee?	
		

  def active?
    part_validation == 'active'
  end


  def active_or_general?
    part_validation.include?('general') || active?
  end

  def active_or_personal?
    part_validation.include?('personal') || active?
  end

  def active_or_c_address?
    part_validation.include?('c_address') || active?
  end

  def active_or_p_address?
    part_validation.include?('p_address') || active?
  end

  def active_or_nominee?
    part_validation.include?('nominee') || active?
  end


end

rv/rv/app/models/pgfeed.rb
class Pgfeed < ActiveRecord::Base
end

rv/rv/app/models/state_master.rb
class StateMaster < ActiveRecord::Base
end

rv/rv/app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

rv/rv/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:session_limitable,
         :recoverable, :rememberable, :trackable, :validatable,:timeoutable,:confirmable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  
def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
end
end

rv/rv/app/helpers/banks_helper.rb
module BanksHelper
end

rv/rv/app/helpers/feeds_helper.rb
module FeedsHelper
end

rv/rv/app/helpers/funds_helper.rb
module FundsHelper
end

rv/rv/app/helpers/kycs_helper.rb
module KycsHelper
end

rv/rv/app/helpers/transactions_helper.rb
module TransactionsHelper
end

rv/rv/app/views/transactions/cams1.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
       <form method="post" action="https://fundsnet.camsonline.com/ecrms/stp/fnStpSystematic.aspx">
               <input type="text" name="Usrcode" value="rupeevest" />
               <input type="text" name="pass" value="qwerty12!@" />
               <input type="file" enctype="multipart/form-data" name="Uploadfile"  />
               <input type="submit" />
       </form>
</body>
</html>

 

rv/rv/app/views/transactions/cams_upload_feed.html.erb
<%= @sh %>

<% if current_user.id == 1 %>

doneeee



<%= form_tag cams_import_feed_transactions_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>









<% end %>

rv/rv/app/views/transactions/confirmation.html.erb
<%= @err %>

<%= @amt %>

<%= @amt1 %>
transaction done

<%= button_to "Karvy feed", { :controller => "transactions", :action => "karvy_upload_feed"} %>
<%= button_to "Karvy feed", { :controller => "transactions", :action => "cams_upload_feed"} %>

rv/rv/app/views/transactions/edit_individual.html.erb
<%= form_tag update_individual_transactions_path :method => :put do %>
  <% for transaction in @transactions %>
    <%= fields_for "transactions[]", transaction do |f| %>

    <% if transaction.tr_mode == "SIP" %>
		<h2><%= h transaction.fund_id %></h2>
        <%= f.label :amount %>
  		<%= f.number_field :amount %>
     	<%= f.label :sip_start_date %>
  		<%= f.date_field :sip_start_date %>
  		<%= f.label :sip_installments %>
  		<%= f.number_field :sip_installments %>
  		<%= f.label :sip_frequency %>
  		<%= f.select :sip_frequency, ["Monthly","Weekly","Bi-Monthly"] %>
  	<% end %>

  	<% if transaction.tr_mode == "Lumpsum" %>
		<h2><%= h transaction.fund_id %></h2>
        <%= f.label :amount %>
  		<%= f.number_field :amount %>
 		<%= f.label :reinvestment_tag %>
  		<%= f.text_field :reinvestment_tag %>
  	<% end %>

    <% end %>
  <% end %>
  <p><%= submit_tag "Submit" %></p>
<% end %>

rv/rv/app/views/transactions/index.html.erb

<% if @sip_lumpsum == 1 %>
<%= form_tag edit_individual_transactions_path do %>
	<table class="table table-bordered">

		<thead>
			<tr>
				<th></th>
				<th>Scheme Name</th>
				<th>Folio</th>
				<th>SIP Day</th>
				<th>No of months</th>
				<th>Dividend Option</th>
				<th>Amount</th>
			</tr>
		</thead>

	<% @transactions_invoice.each do |transaction| %>
	<% @fund = Fund.find_by_id(transaction.fund_id) %>
		<tbody>

		    <tr>
		      <td><%= check_box_tag "transaction_ids[]", transaction.id %></td>
		      <td><%= @fund.scheme_name %></td>      
		      <td><%= transaction.folio_id %></td>
		      <td><%= transaction.sip_start_date %></td>
		      <td><%= transaction.sip_installments %></td>
		      <td><%= transaction.reinvestment_tag %></td>
		      <td><%= transaction.amount %></td>
		      
			</tr>
		</tbody>

	  <% end %>
	</table>

<%= button_to "Cams feed", { :controller => "transactions", :action => "cams_upload_feed"} %>
<%= button_to "Karvy feed2222222", { :controller => "transactions", :action => "karvy_upload_feed"} %>

<p><%= submit_tag "Edit Checked" %></p>

<p><%= submit_tag 'Destroy', :name => 'destroy_button' %></p>
<% end %>

<%= link_to "Make Payement", ru_transactions_path %>
<% end %>
<% if @sip_lumpsum == 0 %>
<%= form_tag edit_individual_transactions_path do %>

	<table class="table table-bordered">

		<thead>
			<tr>
				<th></th>
				<th>Scheme Name</th>
				<th>Folio</th>
				<th>Transaction ID</th>
				<th>Amount</th>
				<th>Dividend Option</th>
			</tr>
		</thead>

	<% @transactions_invoice.each do |transaction| %>
	<% @fund = Fund.find_by_id(transaction.fund_id) %>
		<tbody>

		    <tr>
		      <td><%= check_box_tag "transaction_ids[]", transaction.id %></td>	
		      <td><%= @fund.scheme_name %></td>      
		      <td><%= transaction.folio_id %></td>
		      <td><%= transaction.tr_id %></td>
		      <td><%= transaction.amount %></td>
		      <td><%= transaction.reinvestment_tag %></td>
			</tr>
		</tbody>

	  <% end %>
	</table>

<p><%= submit_tag "Edit Checked" %></p>

<p><%= submit_tag 'Destroy', :name => 'destroy_button' %></p>
<% end %>

<%= link_to "Make Payement", ru_transactions_path %>
<%end%>



<% if @redemption == 1 %>

<table class="table table-bordered">

		<thead>
			<tr>
				<th>Scheme Name</th>
				<th>Folio</th>
				<th>Transaction ID</th>
				<th>Redemtion Type</th>
			</tr>
		</thead>

	<% @transactions_redeem.each do |transaction| %>
	<% @fund = Fund.find_by_id(transaction.fund_id) %>
		<tbody>

		    <tr>
		      <td><%= @fund.scheme_name %></td>      
		      <td><%= transaction.folio_id %></td>
		      <td><%= transaction.tr_id %></td>
		      <td><%= transaction.tr_mode %></td>
			</tr>
		</tbody>

	  <% end %>
	</table>

 <%= button_to "Redeem (Upload Cams Data)", :controller => 'transactions', :action => 'cams_upload_feed'  %>


<% end %>




rv/rv/app/views/transactions/investment.html.erb
<script type="text/javascript">
$(document).ready(function () {
$("#txn").change(function(){
  if ($("#txn").val()=="SIP") {$(".sip").show(); }
  if ($("#txn").val()=="Lumpsum") {$(".sip").hide();  }
  })

});



</script>

<%= form_tag invoice_transactions_path do %>
<h3>Select Bank <%= select_tag "bankid", options_from_collection_for_select(@banks, "id", "name_of_bank") %><br></h3>

Transaction Mode :<%= select_tag "tr_mode", options_for_select(["Lumpsum","SIP"]),:id => "txn" %><br>

-----------------------------------------------------------------------------------------------------------------<br>
<% @funds.each do |fund| %>
<h4><%= fund.scheme_name %><br></h4>	
<%= hidden_field_tag "transactions[][liq_non]", fund.category %>
<%= hidden_field_tag "transactions[][registrar]", fund.registrar %>
<%= hidden_field_tag "transactions[][user_id]", current_user.id %>
<%= hidden_field_tag "transactions[][fund_id]", fund.id %>
Transaction Type :<%= select_tag "transactions[][tr_type]", options_for_select([["Purchase","P"],["Redeem","R"]]) %><br>

<% holding1 = Holding.find(:first, :conditions => ["user_id = ? AND fund_id = ? ",current_user.id,fund.id]) %>
<% holding2 = Holding.find(:first, :conditions => ["user_id = ? AND amc = ? ",current_user.id,fund.registrar_amc_code]) %>
<% if holding1 %>
Folio :<%= select_tag "transactions[][folio_id]", options_for_select([holding1.folio]) %><br>
<% elsif holding2 %>
Folio :<%= select_tag "transactions[][folio_id]", options_for_select([holding2.folio]) %><br>
<% else %>
Folio :<%= select_tag "transactions[][folio_id]", options_for_select([["New",'']]) %><br>
<%end%>






Amount(in Rs.) <%= number_field_tag "transactions[][amount]", fund.min_investment %><br>

<div class="sip" style="display: none;">
Investment Date :<%= date_field_tag "transactions[][sip_start_date]"%><br>
No. of installments :<%= number_field_tag "transactions[][sip_installments]" %><br>
Frequency :<%= select_tag "transactions[][sip_frequency]", options_for_select(["Monthly","Weekly","Bi-Monthly"]) %><br>

</div>


<% if fund.fund_type == "Dividend" %>
Dividend Option :<%= select_tag "transactions[][reinvestment_tag]", options_for_select([["Reinvest","Y"],["Payout","N"]]) %><br>
<% else %>
Dividend Option :<%= select_tag "transactions[][reinvestment_tag]", options_for_select([["Growth","Z"]]) %><br>
<% end %>

<%= hidden_field_tag "transactions[][pg_tr_status]", "Invoice" %>
<%= hidden_field_tag "transactions[][registrar_tr_status]", "Invoice" %>

----------------------------------------------------------------------------------------------------------------------
<br>

<% end %>

This is a :<%= select_tag "euin", options_for_select([["Execution Only","N"],["Advisory Based","Y"]]) %><br> transaction

<%= submit_tag "Do Transaction" %>
<% end %>	






rv/rv/app/views/transactions/invoice.html.erb
<% if @sip_lumpsum == 1 %>

	<table class="table table-bordered">

		<thead>
			<tr>
				<th>Scheme Name</th>
				<th>Folio</th>
				<th>SIP Day</th>
				<th>No of months</th>
				<th>Dividend Option</th>
				<th>Amount</th>
					
			</tr>
		</thead>

	<% @transactions_invoice.each do |transaction| %>
	<% @fund = Fund.find_by_id(transaction.fund_id) %>
		<tbody>

		    <tr>
		      <td><%= @fund.scheme_name %></td>      
		      <td><%= transaction.folio_id %></td>
		      <td><%= transaction.sip_start_date %></td>
		      <td><%= transaction.sip_installments %></td>
		      <td><%= transaction.reinvestment_tag %></td>
		      <td><%= transaction.amount %></td>
		      
			</tr>
		</tbody>

	  <% end %>
	</table>




<%else %>


	<table class="table table-bordered">

		<thead>
			<tr>
				<th>Scheme Name</th>
				<th>Folio</th>
				<th>Transaction ID</th>
				<th>Amount</th>
				<th>Dividend Option</th>
			</tr>
		</thead>

	<% @transactions_invoice.each do |transaction| %>
	<% @fund = Fund.find_by_id(transaction.fund_id) %>
		<tbody>

		    <tr>
		      <td><%= @fund.scheme_name %></td>      
		      <td><%= transaction.folio_id %></td>
		      <td><%= transaction.tr_id %></td>
		      <td><%= transaction.amount %></td>
		      <td><%= transaction.reinvestment_tag %></td>
			</tr>
		</tbody>

	  <% end %>
	</table>

<%end%>

rv/rv/app/views/transactions/karvy1.html.erb
<%= @response %>

rv/rv/app/views/transactions/karvy_upload_feed.html.erb
<%= @sh %>

<br>

<%= @ph %>

rv/rv/app/views/transactions/ru.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
       <form method="post" action="https://www.billdesk.com/pgidsk/pgmerc/RUPVESTMFRedirect.jsp">
               <input type="text" name="msg" value="RUPVESTMF|27|1232465646546|2.00|HDF|NA|NA|INR|DIRECT|R|rupvestmf|NA|NA|F|NA|NA|ARN-86572|HDFCMFD-NA-NA-NA|LIQUID|RESIDENT-15425-NA-NA-NA-NA-L-NA-NA|20140422161151-2.00-NA-NA-NA|https://rupeevest.com/transactions/ru|1283C42EA00EF98EE9BA3BB4D4E732928B97E50BF32E20B2ADC1664701050426" />
               <input type="submit" />
       </form>
</body>
</html>




<%= params[:msg] %>

rv/rv/app/views/transactions/ru2.html.erb
<table class="table table-bordered">

		<thead>
			<tr>
				
				<th>Scheme Name</th>
				<th>Folio</th>
				<th>Transaction ID</th>
				<th>Amount</th>
				<th>Dividend Option</th>
			</tr>
		</thead>

	<% @transactions_pg.each do |transaction| %>
	<% @fund = Fund.find_by_id(transaction.fund_id) %>
		<tbody>

		    <tr>
		      <td><%= @fund.scheme_name %></td>      
		      <td><%= transaction.folio_id %></td>
		      <td><%= transaction.tr_id %></td>
		      <td><%= transaction.amount %></td>
		      <td><%= transaction.reinvestment_tag %></td>
			</tr>
		</tbody>

	  <% end %>
	</table>


<%= @msgtopg %>

<%= form_tag confirmation_transactions_path :method => :put do %>
   <%= text_field_tag "msgpg" %>
  <p><%= submit_tag "Submit" %></p>
<% end %>



rv/rv/app/views/transactions/switch.html.erb
<script type="text/javascript">


$(document).ready(function () {

$(".partial_full").change(function(){
	var parent = $(this).parent().parent();
	var targetTextBox = parent.find('.amt');
  	var targetFixedBox = parent.find('.amt1');

  if ($(this).val()=="Partial Redemption") {
	targetTextBox.show();
	targetFixedBox.hide();
	   }
  if ($(this).val()=="Full Redemption") {
  	targetTextBox.hide();
	targetFixedBox.show();}
  	})



});

</script>



Switch from:

<table class="table table-bordered">

		<thead>
			<tr>
				<th>Scheme Name</th>
				<th>Units Held</th>
				<th>Buy Value</th>
				<th>Current Value</th>
				<th>Gains/Losses</th>
				<th>Return</th>
			</tr>
		</thead>

	<% fund = Fund.find_by_id(@holding.fund_id) %>
		<tbody>

		    <tr>
		      <td><%= fund.scheme_name %></td>      
		      <td><%= @holding.units %></td>
		      <td><%= @holding.buy_value %></td>
		      <td><%= (@holding.units * fund.nav).round(2) %></td>
		      <td><%= ((@holding.units * fund.nav) - @holding.buy_value).round(2)  %></td>
		      <td><%= ((((@holding.units * fund.nav) - @holding.buy_value)/@holding.buy_value)*100).round(2)  %>%</td>
		     
			</tr>
		</tbody>

	 
</table>




<br>Switch to<br>:



<%= form_tag switch_transact_transactions_path do %>

<table class="table table-bordered">
<thead>
  <tr>
    <th>Fund Name</th>
    <th>Category</th>
    <th>Average AUM</th>
    <th>Fund Type</th>
    <th>Expense Ratio</th>
    <th>Check</th> 
  </tr>
</thead>
<tbody>
  <% @fundsto.each do |fund| %>
    <tr>
      <td><%= link_to "#{fund.scheme_name}", fund_path(fund.id) %></td>
      <td><%= fund.category %></td>
      <td><%= fund.net_assets %></td>
      <td><%= fund.fund_type %></td>
      <td><%= fund.expense_ratio %></td>
      <td><%= radio_button_tag "fund_id_switch", fund.id %></td> 
    </tr>
  <% end %>
 </tbody>

</table>


<%= select_tag "partial_or_full", options_for_select(["Partial Redemption","Full Redemption"]),:class => "partial_full" %></td>

<div class = "amt"> Please fill the amount to be switched :<%= number_field_tag "amount"%></div>
<div class = "amt1" style="display: none;">Units switched :<%= @holding.units %></div>

<p><%= submit_tag "Switch" %></p>
<% end %>

rv/rv/app/views/transactions/switch_transact.html.erb
<%= @a %>

rv/rv/app/views/transactions/transact.html.erb



<%= form_tag invoice_transactions_path do %>



<h3>Select Bank <%= select_tag "bankid", options_from_collection_for_select(@banks, "id", "name_of_bank") %><br></h3>



-----------------------------------------------------------------------------------------------------------------<br>
<% if @a == 1 %>
<script type="text/javascript">
$(document).ready(function () {
$("#txn").change(function(){
  if ($("#txn").val()=="SIP") {$(".sip").show(); }
  if ($("#txn").val()=="Lumpsum") {$(".sip").hide();  }
  })

});

</script>

Transaction Mode :<%= select_tag "tr_mode", options_for_select(["Lumpsum","SIP"]),:id => "txn" %><br>

<% @funds.each do |fund| %>
<h4><%= fund.scheme_name %><br></h4>	
<%= hidden_field_tag "transactions[][liq_non]", fund.category %>
<%= hidden_field_tag "transactions[][registrar]", fund.registrar %>
<%= hidden_field_tag "transactions[][user_id]", current_user.id %>
<%= hidden_field_tag "transactions[][fund_id]", fund.id %>
Transaction Type :<%= select_tag "transactions[][tr_type]", options_for_select(["Purchase","P"]) %><br>
<% holding1 = Holding.find(:first, :conditions => ["user_id = ? AND fund_id = ? ",current_user.id,fund.id]) %>
<% holding2 = Holding.find(:first, :conditions => ["user_id = ? AND amc = ? ",current_user.id,fund.registrar_amc_code]) %>
<% if holding1 %>
Folio :<%= select_tag "transactions[][folio_id]", options_for_select([holding1.folio]) %><br>
<% elsif holding2 %>
Folio :<%= select_tag "transactions[][folio_id]", options_for_select([holding2.folio]) %><br>
<% else %>
Folio :<%= select_tag "transactions[][folio_id]", options_for_select(["New"]) %><br>
<%end%>
Amount(in Rs.) <%= number_field_tag "transactions[][amount]", fund.min_investment %><br>

<div class="sip" style="display: none;">
Investment Date :<%= date_field_tag "transactions[][sip_start_date]"%><br>
No. of installments :<%= number_field_tag "transactions[][sip_installments]" %><br>
Frequency :<%= select_tag "transactions[][sip_frequency]", options_for_select(["Monthly","Weekly","Bi-Monthly"]) %><br>

</div>


<% if fund.fund_type == "Dividend" %>
Dividend Option :<%= select_tag "transactions[][reinvestment_tag]", options_for_select([["Reinvest","Y"],["Payout","N"]]) %><br>
<% else %>
Dividend Option :<%= select_tag "transactions[][reinvestment_tag]", options_for_select([["Growth","Z"]]) %><br>
<% end %>

<%= hidden_field_tag "transactions[][pg_tr_status]", "Invoice" %>
<%= hidden_field_tag "transactions[][registrar_tr_status]", "Invoice" %>

----------------------------------------------------------------------------------------------------------------------
<br>


<% end %>

<% end %>

<% if @a == 0 %>

<script type="text/javascript">


$(document).ready(function () {

$(".partial_full").change(function(){
	var parent = $(this).parent().parent();
	var targetTextBox = parent.find('.amt');
  	var targetFixedBox = parent.find('.amt1');

  if ($(this).val()=="Partial Redemption") {
	targetTextBox.show();
	targetFixedBox.hide();
	   }
  if ($(this).val()=="Full Redemption") {
  	targetTextBox.hide();
	targetFixedBox.show();}
  	})



});

</script>




<table class="table table-bordered">
	<tbody>
		
			<% @holdings.each do |holding| %>
			<% fund = Fund.find_by_id(holding.fund_id) %>	
			<tr>
			<div class = "master">		
			<%= hidden_field_tag "transactions[][liq_non]", fund.category %>
			<%= hidden_field_tag "transactions[][registrar]", fund.registrar %>
			<%= hidden_field_tag "transactions[][user_id]", current_user.id %>
			<%= hidden_field_tag "transactions[][fund_id]", fund.id %>
			<td><%= fund.scheme_name %></td>
			<td><%= select_tag "transactions[][folio_id]",  options_for_select([holding.folio]) %>
			<td><%= holding.buy_value %></td>
			<td><div class =  "abc"><%= holding.units %></div></td>
			<td><%= (holding.units * fund.nav).round(2) %></td>
			<td><%= select_tag "transactions[][tr_type]", options_for_select([["Redeem","R"]]) %></td>
			<td><%= select_tag "transactions[][tr_mode]", options_for_select(["Partial Redemption","Full Redemption"]),:class => "partial_full" %></td>

			<td><div class = "amt"><%= number_field_tag "transactions[][amount]"%></div>
				<div class = "amt1" style="display: none;"><%= holding.buy_value %></td>
			
			<td><%= number_field_tag "transactions[][units]"%></td>
			

			<%= hidden_field_tag "transactions[][pg_tr_status]", "Invoice" %>
			<%= hidden_field_tag "transactions[][registrar_tr_status]", "Invoice" %>
			</div>
			</tr>
			<% end %>
		
	</tbody>

</table>


















<% end %>

This is a :<%= select_tag "euin", options_for_select([["Execution Only","N"],["Advisory Based","Y"]]) %><br> transaction

<%= submit_tag "Do Transaction" %>
<% end %>	




