rv/config/routes.rb
Rv::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root :to => 'static_pages#index'
  get "academics/video"
  get "academics/videos"
  get "academics/images"
  get "academics/videoteaser"
  get "transactions/karvy1"
  get "transactions/cams1"
  match '/',    to: 'static_pages#index',    via: 'get'
  match '/',    to: 'static_pages#index',    via: 'post'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/products', to: 'static_pages#products', via: 'get'
  match '/account', to: 'static_pages#account', via: 'get'
  match '/sip_registration', to: 'static_pages#sip_registration', via: 'get'
  match '/import_sip_registration', to: 'static_pages#import_sip_registration', via: 'post'
  match '/import_sip_transaction', to: 'static_pages#import_sip_transaction', via: 'post'
  match '/sip_transactions', to: 'static_pages#sip_transactions', via: 'get'
  match '/portfolio', to: 'static_pages#portfolio', via: 'get'
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  get "contacts/welcome_email"
  resources :kycs
  resources :kyc_steps
  resources :funds
  post "kycs/update_holding_type"
  post "kycs/new"
  resources :banks
  resources :transactions do 
    collection do
      get :investment
      post :invoice
      post :edit_individual
      post :update_individual
      get :ru
      post :ru
      post :confirmation
      post :cams_upload_feed
      post :cams_import_feed
      post :transact
      get :switch
      post :switch_transact
      post :karvy_upload_feed
    end
  end

  

end

rv/app/models/kyc.rb
class Kyc < ActiveRecord::Base

 	validates_presence_of :first_name, :last_name,:pan, :if => :active_or_general?
 	validates_format_of :pan, :with => /\A([A-Za-z]{5}\d{4}[A-Za-z]{1})\Z/i, :if => :active_or_general?
 	validates_presence_of :father_spouse_name,:nationality, :if => :active_or_personal?
	validates_presence_of :c_house_no, :c_street_name, :c_area_name,:c_email,:c_postal_code, :if => :active_or_c_address?
	validates_format_of :c_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :if => :active_or_c_address? 
	validates_format_of :c_postal_code, :with => /\A(\d{6})\Z/i, :if => :active_or_c_address? 
	validates_presence_of :c_mobile, :if => :active_or_c_address? 
	validates_presence_of :p_house_no, :p_street_name, :p_area_name,:p_email,:p_postal_code, :if => :active_or_p_address?
	validates_format_of :p_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :if => :active_or_p_address? 
	validates_format_of :p_postal_code, :with => /\A(\d{6})\Z/i, :if => :active_or_p_address? 
	validates_presence_of :p_mobile, :if => :active_or_p_address? 
	validates_presence_of :nominee_name,:nominee_relation,:nominee_address, :if => :active_or_nominee?	
		

  def active?
    part_validation == 'active'
  end


  def active_or_general?
    part_validation.include?('general') || active?
  end

  def active_or_personal?
    part_validation.include?('personal') || active?
  end

  def active_or_c_address?
    part_validation.include?('c_address') || active?
  end

  def active_or_p_address?
    part_validation.include?('p_address') || active?
  end

  def active_or_nominee?
    part_validation.include?('nominee') || active?
  end


end

rv/app/controllers/kycs_controller.rb
class KycsController < ApplicationController


  def update_holding_type
    if params[:commit] == '1'
      current_user.holding_type = '1'
      current_user.tax_status = 1
      current_user.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '1'
      kyc.save 
    end
    if params[:commit] == '2'
      current_user.holding_type = '4'
      current_user.tax_status = 21
      current_user.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '1'
      kyc.save 
    end
    if params[:commit] == '3'
      current_user.holding_type = '5'
      current_user.tax_status = 11
      current_user.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '1'
      kyc.save 
    end
    if params[:commit] == '4'
      current_user.holding_type = '7'
      current_user.tax_status = 2
      current_user.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '1'
      kyc.save 
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '4'
      kyc.save 
    end
    if params[:commit] == '5'
      current_user.holding_type = '6'
      current_user.tax_status = 3
      current_user.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '1'
      kyc.save 
    end
    if params[:commit] == '6'
      current_user.holding_type = '2'
      current_user.tax_status = 1
      current_user.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '1'
      kyc.save 
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '2'
      kyc.save 
    end
    if params[:commit] == '7'
      current_user.holding_type = '3'
      current_user.tax_status = 1
      current_user.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '1'
      kyc.save 
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '2'
      kyc.save
      kyc = Kyc.new
      kyc.user_id = current_user.id
      kyc.part_validation = 'new'
      kyc.holding_priority = '3'
      kyc.save  
    end


	

  end


  def new
	@kyc = Kyc.find(:first, :conditions => ["user_id = ? AND holding_priority = ? ",current_user.id, params[:priority]])
  	session[:priority] = params[:priority]
  end



  def create

    @kyc = Kyc.new(kyc_params)
    @kyc.part_validation = 'general'
    if @kyc.save		
      current_user.kyc_status = 1 #partial kyc done
      current_user.save
      redirect_to kyc_steps_path
    else
      render :new
    end
  end

  def update
  	   @kyc = Kyc.find(:first, :conditions => ["user_id = ? AND holding_priority = ? ",current_user.id, session[:priority]])
  	   @kyc.part_validation = 'general'
       if @kyc.update_attributes(kyc_params)
       		redirect_to kyc_steps_path
       else
      		render :new
       
       end  
  end

  private
	  def kyc_params
	    params.require(:kyc).permit(:user_id,:holding_priority,:first_name,:last_name,:father_spouse_name,:gender,:marital_status,:date_of_birth,:nationality,:residence_status,
	    	:pan,:proof_of_identity,:c_house_no,:c_street_name,:c_area_name,:c_city_town_village,:c_state,:c_country,:c_postal_code,:c_landline,:c_mobile,:c_email,:c_proof_of_address,
	    	:same,:p_house_no,:p_street_name,:p_area_name,:p_city_town_village,:p_state,:p_country,:p_postal_code,:p_landline,:p_mobile,:p_email,:p_proof_of_address,:annual_income,
	    	:occupation,:pep_status,:nominee_name,:nominee_relation,:nominee_address,:nominee_flag,:nominee_dob,:nominee_gaurdian,:part_validation)
	    
 

	  end


end


	

rv/app/helpers/kycs_helper.rb
module KycsHelper
end

rv/app/views/kycs/new.html.erb
<%= simple_form_for @kyc  do |f| %>

	
			
  <h2>Personal Information</h2>
  	
  	<%= f.input :first_name , label:'Name'%>
	<%= f.input :last_name , label:'Last Name' %>
	
	<%= f.input :pan , label:'PAN' %>
		
  <p><%= f.submit "Save" %></p>
  
<% end %>


rv/app/views/kycs/showkycs.html.erb
<% if user_signed_in? %>
  <%= form_tag(new_kyc_path, :method=>'post') do %>

	 <p>
	   KYC for : <br />
	   <% if current_user.holding_type == '7' %>
	   <%= select_tag("priority", options_for_select([['Minor', '1'],
	                 ['Gaurdian', '4']], '1')) %>
	   <%end%>
	   <% if current_user.holding_type == '3' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1'],
	                 ['2nd Holder', '2'],['3rd Holder','3']], '1')) %>
	   <%end%>
	   <% if current_user.holding_type == '2' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1'],
	                 ['2nd Holder', '2']], '1')) %>
	   <%end%>
	    <% if current_user.holding_type == '1' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>
	     <% if current_user.holding_type == '4' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>
	     <% if current_user.holding_type == '5' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>
	     <% if current_user.holding_type == '6' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>

	 </p>

	 <p>
	   <%= submit_tag 'Submit' %>
	 </p>
  <% end %>
	


  

<%end%>

rv/app/views/kycs/update_holding_type.html.erb

<% if user_signed_in? %>


<%= form_tag(new_kyc_path, :method=>'post') do %>

	 <p>
	   KYC for : <br />
	   <% if current_user.holding_type == '7' %>
	   <%= select_tag("priority", options_for_select([['Minor', '1'],
	                 ['Gaurdian', '4']], '1')) %>
	   <%end%>
	   <% if current_user.holding_type == '3' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1'],
	                 ['2nd Holder', '2'],['3rd Holder','3']], '1')) %>
	   <%end%>
	   <% if current_user.holding_type == '2' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1'],
	                 ['2nd Holder', '2']], '1')) %>
	   <%end%>
	    <% if current_user.holding_type == '1' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>
	     <% if current_user.holding_type == '4' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>
	     <% if current_user.holding_type == '5' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>
	     <% if current_user.holding_type == '6' %>
	   <%= select_tag("priority", options_for_select([['1st Holder', '1']], '1')) %>
	    <%end%>

	 </p>

	 <p>
	   <%= submit_tag 'Submit' %>
	 </p>
<% end %>
	

  

<%end%>